### ISSUE TITLE
Разъясните про "3.1.3 список тегов, которых НЕ должно быть у документа"?

### ISSUE THREAD

**Issue by denizzzka** [cheshirenet/cheshirenet#1]
Зачем это нужно?

3.1.3 список тегов, которых НЕ должно быть у документа, со списком постановщиков

Теги задаются только именами или частичными именами с указанием "иерархия". Логика по тегам и постановщикам "и" (как если бы каждый из этих тегов с каждым постановщиком шел отдельным критерием). Версия документа удовлетворяет критерию, если никто из постановщиков никакой из тегов (в иерархии) не поставил в "да".

**Comment by vbwagner** [comment]
Представим себе что тэг называется "spam" или "эксплицитная эротика". Понятно зачем нужно НЕ получать сообщения, помеченные таким тегом?

**Comment by denizzzka** [comment]
А, конечно!
