### ISSUE TITLE
Как избежать cкачивания дублирующихся сообщений?

### ISSUE THREAD

**Issue by denizzzka** [cheshirenet/cheshirenet#2]
Предположим, у меня произошёл сеанс связи, в котором я скачал некую подборку статей (анекдотов за последние 5 лет, например) из ньюсгруппы.

Потом я подключился к другому пиру, и снова сделал запрос об анекдотах. И мне вновь предложили частично старые, а частично неизвестные мне статьи.

Как планируется избежать дублирования передачи данных в этом случае?

**Comment by stanislavvv** [comment]
Насколько я понимаю, точно так же, как в nntp - по message-id, список которых в nntp получается до того, как будут вытащены сами сообщения.

**Comment by denizzzka** [comment]
Но ведь при вырастании локального архива этот список станет внушительным?

**Comment by stanislavvv** [comment]
Точно так же, как и в крупных nntp-серверах.
Как вариант - спрашивать "что нового после YYYY-MM-DD" (дата-время в соответствии с интервалом хранения, вряд ли вы будете хранить анекдоты вечно и маловероятно, что данные вида "ежедневная газета" недельной давности интересны сегодня).
Посмотрите всё же, как устроен nntp. Там не то чтобы все вопросы решили окончательно, но всё же приблизились к решению достаточно, чтобы кое-что оттуда взять.

**Comment by vbwagner** [comment]
Вы абсолюно правы, Станислав. Не даром у нас в wiki есть раздел relevant RFC. 
Грустно конечно, то что не получается воспользоваться существующей кодовой базой netnews. Но к сожалению, ньюсридеры разучились ходить по гиперссылкам схемы news:.

**Comment by mds99** [comment]
задача, которая решается - синхронизовать состав репозитория хранения. Причем полностью синхронизировать мы по условиям задачи не должны. фильтрацию можно делать не только в процессе отдачи, но и в процессе приема. Таким образом, по сути нужно хранить что-то подобное логу транзакций базы данных  и отдавать именно его, с привязкой к времени локальной операции - ведь все, что мы отдаем, так или иначе обработано нами, либо оставлено как есть по покладанию в архив. Операции тегирования  и прочих локальных модификаций, это отдельные транзакции, со своей привязкой на момент выполнения. 
Таким образом, вполне реально уложить данный процесс в отдачу "бандлов" с данными и локально построенным оглавлением к ним. чтобы принимающий мог на своей стороне отобрать те объекты, которые интересны именно ему, либо транзитны. Дедупликация получается затейливой, но вполне конечной задачей - транзитные данные оставляются как есть, данные для собственных подписок выбираются и из них создаются локальные бандлы для хранения.  Задача отдающей стороны - отработать заявленные принимающим фильтры и не отправлять то, что совсем в них не попадает.  Напоминает что-то вроде messagebus на стероидах.

**Comment by stanislavvv** [comment]
А зачем, собственно, транзитные сообщения как-то отдельно обрабатывать?
Достаточно выставить им режим хранения "транзитный - удалять когда понадобится, но не позже, чем ..." и пусть себе лежат. Если захочется почитать - читаем без доп обработки (может теги расставляем, если надо).

Что касается привязки синхронизации ко времени - тут надо учитывать время прихода сообщения, а не время его создания, чтоб не пропустить сообщения, написанные за тридевять линков.

**Comment by mds99** [comment]
время здесь скорее одно из измерений. Красивый подход изложен вот тут, например. https://awinterman.github.io/simple-scuttle/
Я так понимаю, это и есть блок-чейн.

**Comment by denizzzka** [comment]
Закрываю, так как всё что нужно прояснилось?
