### ISSUE TITLE
Ссылка на цитату в документе

### ISSUE THREAD

**Issue by smeagol74** [cheshirenet/cheshirenet#3]
Добавить в спецификацию ссылок [URL](https://github.com/cheshirenet/cheshirenet/wiki/URL) возможность сослаться на конкретное место в документе, например `chn://uuid?p=25:36` будет ссылаться на часть документа с 25 по 36 символ, если это текстовый документ, или с 25 по 36 секунду если это звуковой файл. Конкретная интерпретация позиции зависит от формата документа.

Тогда при цитировании можно будет указать конкретное место цитирования. И при отображении цитируемого документа можно будет отобразить обсуждение конкретного места, например так, как это было в google wave. И собирать треды обсуждения не по "исторически-сложившейся" структуре, а по логической цепочке обсуждения конкретных фрагментов.

В принципе можно цитаты в цитирующий текст и не помещать вовсе, просто при запросе цитирующего документа сразу же получать и цитируемый. А при отображении цитирующего документа цитируемый текст встраивать программно с возможностью перехода к просмотру цитируемого документа в полном объёме. Это также уменьшит и искажения при цитировании.

**Comment by vbwagner** [comment]
Нет необходимости изобретать какие-то самопальные механизмы, когда существует механизм якорей и через #имя можно сослаться в любое место html документа, помеченное якорем, или элемент XML имеющий ID.

**Comment by smeagol74** [comment]
Позволю себе не согласиться. Система якорей предполагает предварительную довольно специфическую разметку и не позволяет сослаться на любую произвольную часть документа. Опять же далеко не все форматы документов предполагают постановку этих самых якорей.

Например, как часто вы в своих постах расставляете якоря, чтобы при обсуждении можно было адекватно сослаться на конкретное место в тексте?

**Comment by smeagol74** [comment]
Ещё один довод в пользу моего предложения. Расстановка якорей предполагает, что автор документа заранее отметит и поименует все места, на которые в документе можно сослаться. В реальности же это цитирующий выбирает что именно он желает процитировать, а не автор документа. Поэтому предложенный Вами вариант с якорями не будет работать в 99% случаев. Думаю, что будет полезным заранее договориться о едином формате оформления цитат и цитатных ссылок.

**Comment by TarisMarh** [comment]
В случае редактирования документа, такой способ цитирования будет давать сбои. Но ладно, есть версии, так что можно забить. Но вот предсвьте ситуацию: в маленьком письме цитата из статьи, которая цитирет БСЭ и ещё парочку подобных талмудов. Представили себе выкачиваемые объёмы? Просто потому что иначе вытащить эти цитаты не получится. Недостаток предложенного способа проистекает из достоинства системы - отсутствия постоянной связи. Поэтому либо таскаете с эти источники целиком, либо просто включать цитаты в текст и давать ссылки, как это делают - тадам! - в бумажных книгах ещё до Гутенберга. А поскольку в качестве основного онносителя предполагается использовать устройства с ограниченной памятью - смартфоны и планшеты и прочие, то таскать с собой упомянутую выше БСЭ, а так же всю Википедию на нескольких языках и всю библиотеку Конгресса, будет затруднительно. Не говоря уже о архивах YouTube и прочих подобных. На слабых и дорогих соединениях даже картинки режут, а Вы предлагаете таскать с собой звук, видео и энциклопедии.

Это кроме того, что написал Виктор.

**Comment by smeagol74** [comment]
> В случае редактирования документа, такой способ цитирования будет давать сбои.

Нет, не будет. Так как ссылка всегда ведёт на конкретную версию документа, а не на метадокумент. А вся система предполагает, что редактура возможна только выпуском новой версии документа, а не подменой старого содержания.

> Но вот предсвьте ситуацию: в маленьком письме цитата из статьи, которая цитирет БСЭ и ещё парочку подобных талмудов. Представили себе выкачиваемые объёмы?

Да, представил. Тому кто запостит в сеть БСЭ одним атомарным документом и тому кто на него потом будет ссылаться нужно будет забить в голову гвоздь. А в реальности небольшая статья будет оформлена в виде если не самостоятельного документа, то части составного документа, на который и будет сделана ссылка. Плюс ко всему я предложил оставить возможность содержания текста цитаты в тексте комментария. А выкачивание оригинальных цитируемых документов можно всегда оставить на "желание" пользователя. Лично я бы предпочёл уточнить как именно цитата звучала в оригинале и в каком контексте она там была использована прежде, чем воспринимать её в качестве какого либо аргумента. Если кому-то достаточно вставленного цитирующим текста, его право.

> а Вы предлагаете таскать с собой звук, видео и энциклопедии.

Это вам причудилось, я нигде такого не предлагал. Тем более я нигде не предлагал заставлять кого-то это делать. Хотя если возможности пользователя позволяют и он сам того желает, то почему бы и нет.
